# $NetBSD: Makefile,v 1.12 2012/10/25 06:56:52 asau Exp $
#

DISTNAME=		parse-${VERSION}
VERSION=		1.6.6
PKGNAME=		${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=		textproc python
MASTER_SITES=		https://pypi.python.org/packages/c3/e3/c2ca7f10c481b84ba7bf8c35c595ee4825d828fce7838fffc57f0ea0acc9/

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		https://github.com/r1chardj0n3s/parse
COMMENT=		parse() is the opposite of format()
LICENSE=		bsd

.include "../../lang/python/egg.mk"
_PYSETUPTOOLSINSTALLARGS= #

.include "../../mk/bsd.pkg.mk"
