# $NetBSD: Makefile,v 1.12 2012/10/25 06:56:52 asau Exp $
#

DISTNAME=		jmespath-${VERSION}
VERSION=		0.9.0
PKGNAME=		${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=		textproc python
MASTER_SITES=		https://pypi.python.org/packages/8f/d8/6e3e602a3e90c5e3961d3d159540df6b2ff32f5ab2ee8ee1d28235a425c1/

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		https://github.com/jmespath/jmespath.py
COMMENT=		JSON Matching Expressions
LICENSE=		MIT

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
