# $NetBSD$
# -*- mode: makefile; tab-width: 8; indent-tabs-mode: 1 -*-
# vim: ts=8 sw=8 ft=make noet

VERSION=		2.1.4
DISTNAME=		riak-${VERSION}
PKGNAME=		riak-kv-${VERSION}
CATEGORIES=		pagoda
MASTER_SITES=	http://s3.amazonaws.com/downloads.basho.com/riak/2.1/${VERSION}/

.include "../../mk/bsd.pkg.mk"