# $NetBSD$
# -*- mode: makefile; tab-width: 8; indent-tabs-mode: 1 -*-
# vim: ts=8 sw=8 ft=make noet

VERSION=		2.3.5
DISTNAME=		riak-cs-${VERSION}
CATEGORIES=		pagoda
MASTER_SITES=	https://download.rethinkdb.com/dist/
EXTRACT_SUFX=	.tgz

.include "../../mk/bsd.pkg.mk"