#	$NetBSD: sfiles-linux-x86_64.mk,v 1.3 2016/01/22 14:18:42 ryoon Exp $
#
# Created with "make makesfiles"
# Do not edit this file manually!
#
SFILES+=	lib/jvm.cfg
SFILES+=	lib/deploy/messages_es.properties
SFILES+=	lib/deploy/messages_zh_TW.properties
SFILES+=	lib/deploy/messages_fr.properties
SFILES+=	lib/deploy/messages.properties
SFILES+=	lib/deploy/messages_pt_BR.properties
SFILES+=	lib/deploy/messages_de.properties
SFILES+=	lib/deploy/messages_sv.properties
SFILES+=	lib/deploy/messages_ko.properties
SFILES+=	lib/deploy/messages_zh_HK.properties
SFILES+=	lib/deploy/messages_it.properties
SFILES+=	lib/deploy/messages_zh_CN.properties
SFILES+=	lib/deploy/messages_ja.properties
SFILES+=	lib/fontconfig.RedHat.6.bfc
SFILES+=	lib/fontconfig.RedHat.6.properties.src
SFILES+=	lib/fontconfig.SuSE.11.bfc
SFILES+=	lib/fontconfig.SuSE.11.properties.src
SFILES+=	lib/fontconfig.bfc
SFILES+=	lib/fontconfig.properties.src
SFILES+=	lib/javafx.properties
SFILES+=	conf/logging.properties
SFILES+=	conf/management/management.properties
SFILES+=	conf/net.properties
SFILES+=	lib/psfont.properties.ja
SFILES+=	conf/sound.properties
