# $NetBSD$
# -*- mode: makefile; tab-width: 8; indent-tabs-mode: 1 -*-
# vim: ts=8 sw=8 ft=make noet

VERSION=		3.9
DISTNAME=		apache-cassandra-${VERSION}-src
PKGNAME=		cassandra-${VERSION}
CATEGORIES=		pagoda
MASTER_SITES=		http://apache.mirrors.tds.net/cassandra/${VERSION}/

.include "../../mk/bsd.pkg.mk"
