# $NetBSD$
# -*- mode: makefile; tab-width: 8; indent-tabs-mode: 1 -*-
# vim: ts=8 sw=8 ft=make noet

VERSION=		2.2.8
DISTNAME=		apache-cassandra-${VERSION}-bin
PKGNAME=		cassandra-${VERSION}
CATEGORIES=		pagoda
MASTER_SITES=		http://www.apache.org/dyn/closer.lua/cassandra/${VERSION}/

.include "../../mk/bsd.pkg.mk"