# $NetBSD: Makefile,v 1.12 2012/10/25 06:56:52 asau Exp $
#

DISTNAME=		nosexcover-${VERSION}
VERSION=		1.0.10
PKGNAME=		${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=		textproc python
MASTER_SITES=		https://pypi.python.org/packages/79/5e/e882c69e11c7fa1ae1c73f8470294559420593a12ec876acbcd44b4e58e5/nosexcover-1.0.10.tar.gz

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		http://github.com/cmheisel/nose-xcover/
COMMENT=		Extends nose.plugins.cover to add Cobertura-style XML reports
LICENSE=		bsd

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
