# $NetBSD$
# -*- mode: makefile; tab-width: 8; indent-tabs-mode: 1 -*-
# vim: ts=8 sw=8 ft=make noet

VERSION=		1.4.0
DISTNAME=		riak_ts-${VERSION}
CATEGORIES=		pagoda
MASTER_SITES=	http://s3.amazonaws.com/downloads.basho.com/riak_ts/1.4/${VERSION}/

.include "../../mk/bsd.pkg.mk"