# $NetBSD$
# -*- mode: makefile; tab-width: 8; indent-tabs-mode: 1 -*-
#  # vim: ts=8 sw=8 ft=make noet

DISTNAME=		nginx-1.8.1
PKGREVISION=		3	
MAINTAINER=		joerg@NetBSD.org

.include "../../base/nginx/Makefile.common"
