# $NetBSD: Makefile,v 1.21 2015/03/13 14:34:12 taca Exp $

DISTNAME=	bundler-1.10.3
CATEGORIES=	misc

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://gembundler.com/
COMMENT=	Manage your application's dependencies
LICENSE=	mit

RUBYGEM_OPTIONS+=	--format-executable

.include "../../base/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
