PKGDIR= ${.CURDIR}/../../devel/py-pip
FILESDIR= ${.CURDIR}/../../devel/py-pip/files
PATCHDIR= ${.CURDIR}/../../devel/py-pip/patches
ALTERNATIVES_SRC= ${.CURDIR}/../../devel/py-pip/ALTERNATIVES
.include "../../devel/py-pip/Makefile"
.include "../../mk/alternatives.mk"
