PKGDIR= ${.CURDIR}/../../databases/py-sqlite3
FILESDIR= ${.CURDIR}/../../databases/py-sqlite3/files
PATCHDIR= ${.CURDIR}/../../databases/py-sqlite3/patches
.include "../../databases/py-sqlite3/Makefile"
