# $NetBSD$
# -*- mode: makefile; tab-width: 8; indent-tabs-mode: 1 -*-
# vim: ts=8 sw=8 ft=make noet

DISTNAME=		redis-4.0.8
CATEGORIES=		databases
MASTER_SITES=		http://download.redis.io/releases/

MAINTAINER=		braxton@pagodabox.com
HOMEPAGE=		http://redis.io/
COMMENT=		Persistent key-value database with built-in net interface
LICENSE=		modified-bsd

USE_TOOLS+=		gmake pax
USE_LANGUAGES=		c99

.include "../../mk/bsd.prefs.mk"
.include "../../mk/bsd.pkg.mk"
